--Виведіть повні імена лікарів та їх спеціалізації.
SELECT DOCTORS.SURNAME, DOCTORS.NAME, SPECIALIZATIONS.NAME
FROM DOCTORS_SPECIALIZATIONS
	JOIN DOCTORS ON DOCTORS_SPECIALIZATIONS.DOCTOR_ID = DOCTORS.ID
	JOIN SPECIALIZATIONS ON DOCTORS_SPECIALIZATIONS.SPECIALIZATION_ID = SPECIALIZATIONS.ID;
	
--Виведіть прізвища та зарплати (сума ставки та надбавки) лікарів, які не перебувають у відпустці
SELECT DOCTORS.SURNAME, (DOCTORS.SALARY + DOCTORS.PREMIUM) AS TOTAL
FROM DOCTORS
WHERE DOCTORS.ID NOT IN (SELECT DOCTOR_ID
						FROM VACATIONS)

--Виведіть назви палат, які знаходяться у відділенні «Intensive Treatment».
SELECT WARDS.NAME
FROM WARDS
WHERE DEPARTMENT_ID = (SELECT ID
					  FROM DEPARTMENTS
					  WHERE NAME = 'Emergency Department')
					  
--Виведіть назви відділень без повторень, які спонсоруються компанією «Umbrella Corporation».
SELECT DISTINCT DEPARTMENTS.NAME
FROM DONATIONS
	JOIN DEPARTMENTS ON DONATIONS.DEPARTMENT_ID = DEPARTMENTS.ID
	JOIN SPONSORS ON DONATIONS.SPONSOR_ID = SPONSORS.ID
WHERE SPONSORS.NAME = 'HealthFirst Clinic'

--Виведіть усі пожертвування за останній місяць у вигляді: 
--відділення, спонсор, сума пожертвування, дата пожертвування.

SELECT DEPARTMENTS.NAME, SPONSORS.NAME, DONATIONS.AMOUNT, DONATIONS.DONATION_DATE
FROM DONATIONS
	JOIN DEPARTMENTS ON DONATIONS.DEPARTMENT_ID = DEPARTMENTS.ID
	JOIN SPONSORS ON DONATIONS.SPONSOR_ID = SPONSORS.ID
WHERE EXTRACT(MONTH FROM DONATIONS.DONATION_DATE) = EXTRACT(MONTH FROM CURRENT_DATE)

--Виведіть прізвища лікарів із зазначенням відділень,
--в яких вони проводять обстеження. Враховуйте обстеження, які проводяться лише у будні дні.

SELECT DOCTORS.SURNAME, DEPARTMENTS.NAME, EXAMINATIONS.DAY_OF_WEEK
FROM DOCTORS_EXAMINATIONS
	JOIN DOCTORS ON DOCTORS_EXAMINATIONS.DOCTOR_ID = DOCTORS.ID
	JOIN EXAMINATIONS ON DOCTORS_EXAMINATIONS.EXAMINATION_ID = EXAMINATIONS.ID
	JOIN DEPARTMENTS ON DEPARTMENTS.ID = DOCTORS.DEPARTMENT_ID
WHERE EXAMINATIONS.DAY_OF_WEEK < 6
ORDER BY DOCTORS.SURNAME

--Виведіть назви відділень, які отримували пожертву-вання
--у розмірі понад 100000, із зазначенням їх лікарів.

SELECT DEPARTMENTS.NAME, DOCTORS.SURNAME
FROM DONATIONS
	JOIN DEPARTMENTS ON DONATIONS.DEPARTMENT_ID = DEPARTMENTS.ID
	JOIN DOCTORS ON DEPARTMENTS.ID = DOCTORS.DEPARTMENT_ID
WHERE DONATIONS.AMOUNT > 1000::MONEY

--Виведіть назви відділень, в яких лікарі не отримують надбавки.
SELECT DEPARTMENTS.NAME
FROM DEPARTMENTS
	JOIN DOCTORS ON DEPARTMENTS.ID = DOCTORS.DEPARTMENT_ID
WHERE DOCTORS.PREMIUM = 0::MONEY

--Виведіть назви відділень і назви захворювань, обстеження з яких вони проводили за останні півроку.
SELECT DEPARTMENTS.NAME, DISEASES.NAME
FROM EXAMINATIONS
	JOIN DEPARTMENTS ON EXAMINATIONS.DEPARTMENT_ID = DEPARTMENTS.ID
	JOIN DISEASES ON DISEASES.ID = EXAMINATIONS.DISEASE_ID
	JOIN EXAMINATIONS_FACT ON EXAMINATIONS_FACT.EXAMINATION_ID = EXAMINATIONS.ID
WHERE EXTRACT(MONTH FROM CURRENT_DATE) - EXTRACT(MONTH FROM EXAMINATIONS_FACT.EXAMINATION_DATE) < 6 

