--Показати кількість овочів.
SELECT COUNT(*)
FROM FRUITS_AND_VEGETABLES
WHERE PRODUCT_TYPE = 'vegetable';

--Показати кількість фруктів
SELECT COUNT(*)
FROM FRUITS_AND_VEGETABLES
WHERE PRODUCT_TYPE = 'fruit';

--Показати кількість овочів та фруктів заданого кольору
SELECT COUNT(*), PRODUCT_TYPE
FROM FRUITS_AND_VEGETABLES
WHERE LOWER(COLOR) = 'orange'
GROUP BY PRODUCT_TYPE;


--Показати кількість овочів та фруктів кожного кольору
SELECT (
			SELECT COUNT(*)
			FROM FRUITS_AND_VEGETABLES
			WHERE PRODUCT_TYPE = 'fruit' AND COLOR = F_V.COLOR
		) AS FRUITS_COUNT,
		(
			SELECT COUNT(*)
			FROM FRUITS_AND_VEGETABLES
			WHERE PRODUCT_TYPE = 'vegetable'  AND COLOR = F_V.COLOR
		) AS VEGS_COUNT,
		COLOR
FROM FRUITS_AND_VEGETABLES AS F_V
GROUP BY COLOR;

						
--Показати колір мінімальної кількості овочів та фруктів						
SELECT COLOR, PRODUCT_TYPE
FROM FRUITS_AND_VEGETABLES
GROUP BY COLOR, PRODUCT_TYPE
HAVING COUNT(*) = (
    SELECT MIN(RECORD)
    FROM (
        SELECT COUNT(*) AS RECORD, PRODUCT_TYPE
        FROM FRUITS_AND_VEGETABLES
        GROUP BY COLOR, PRODUCT_TYPE
    ) AS MIN_RECORD
    WHERE MIN_RECORD.PRODUCT_TYPE = FRUITS_AND_VEGETABLES.PRODUCT_TYPE
);

--Показати колір максимальної кількості овочів та фруктів					
SELECT COLOR, PRODUCT_TYPE
FROM FRUITS_AND_VEGETABLES
GROUP BY COLOR, PRODUCT_TYPE
HAVING COUNT(*) = (
    SELECT MAX(RECORD)
    FROM (
        SELECT COUNT(*) AS RECORD, PRODUCT_TYPE
        FROM FRUITS_AND_VEGETABLES
        GROUP BY COLOR, PRODUCT_TYPE
    ) AS MAX_RECORD
    WHERE MAX_RECORD.PRODUCT_TYPE = FRUITS_AND_VEGETABLES.PRODUCT_TYPE
);			

--Показати мінімальну калорійність овочів та фруктів.
SELECT MIN(CALORIC_CONTENT), PRODUCT_TYPE
FROM FRUITS_AND_VEGETABLES
GROUP BY PRODUCT_TYPE;

--Показати максимальну калорійність овочів та фруктів
SELECT MAX(CALORIC_CONTENT), PRODUCT_TYPE
FROM FRUITS_AND_VEGETABLES
GROUP BY PRODUCT_TYPE;

--Показати середню калорійність овочів та фруктів.
SELECT ROUND(AVG(CALORIC_CONTENT), 2), PRODUCT_TYPE
FROM FRUITS_AND_VEGETABLES
GROUP BY PRODUCT_TYPE;


--Показати фрукт з мінімальною калорійністю.
SELECT PRODUCT_NAME 
FROM FRUITS_AND_VEGETABLES
WHERE PRODUCT_TYPE = 'fruit' 
		AND CALORIC_CONTENT = (
								SELECT MIN(CALORIC_CONTENT)
								FROM FRUITS_AND_VEGETABLES
								WHERE PRODUCT_TYPE = 'fruit');
												
--Показати фрукт з максимальною калорійністю
SELECT PRODUCT_NAME 
FROM FRUITS_AND_VEGETABLES
WHERE PRODUCT_TYPE = 'fruit' 
		AND CALORIC_CONTENT = (
								SELECT MAX(CALORIC_CONTENT)
								FROM FRUITS_AND_VEGETABLES
								WHERE PRODUCT_TYPE = 'fruit');



